name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # Passe an, falls dein Default-Branch anders heißt

permissions:
  pages: write     # Erlaubt das Veröffentlichen auf GitHub Pages
  id-token: write  # Erforderlich für das deploy-pages Action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build production assets
        run: npm run build

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
